#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/drivers/gpu/drm/msm -I$(srctree)/drivers/gpu/drm/msm/dsi-staging -I$(srctree)/drivers/gpu/drm/msm/dp
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/clk/qcom
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung_lego

obj-y  += ss_dsi_panel_S6E3FC3_AMS646YD04.o
