#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/drivers/gpu/drm/msm -I$(srctree)/drivers/gpu/drm/msm/dsi-staging
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung

obj-y  += ss_dsi_panel_S6E3HA9_AMB666WS04.o
obj-y  += ss_dsi_smart_dimming_S6E3HA9_AMB666WS04.o
obj-y  += ss_dsi_interpolation_S6E3HA9_AMB666WS04.o