#
# Self Display Object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/drivers/gpu/drm/msm -I$(srctree)/drivers/gpu/drm/msm/dsi-staging
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung

obj-y += self_display_FA7.o
obj-y += self_display_FA9.o
obj-y += self_display_HA8.o
obj-y += self_display_HA9.o
obj-y += self_display_XA0.o
