#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".o
#
ccflags-y := -I$(srctree)/include/drm -I$(srctree)/drivers/gpu/drm/msm -I$(srctree)/drivers/gpu/drm/msm/dsi-staging
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung/BLIC_LM36274

obj-y  += ss_dsi_panel_NT36672A_PM6300JB1.o
